apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- "../../../../../manifests/apps/media/tubesync/base"
- http-route.yaml
patches:
- path: patches/remove-talos-backup-namespace-tubesync.yaml
- path: patches/remove-talos-backup-persistentvolumeclaim-config-pvc.yaml
- path: patches/remove-talos-backup-persistentvolumeclaim-media-pvc.yaml
