apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-storage
  namespace: comfyui
  labels:
    backup-exempt:
  annotations:
    storage.vanillax.dev/backup-exempt-reason:
spec:
  storageClassName: truenas-nfs-csi
  volumeName: ""
