apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project-zomboid
resources:
- "../../../../../manifests/apps/home/project-zomboid/base"
patches:
- path: patches/remove-talos-backup-namespace-project-zomboid.yaml
- path: patches/remove-talos-backup-persistentvolumeclaim-zomboid-data.yaml
- path: patches/remove-talos-backup-persistentvolumeclaim-zomboid-server-files.yaml
