apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich
resources:
- "../../../../../manifests/apps/media/immich/base"
- httproute.yaml
patches:
- path: patches/remove-talos-backup-namespace-immich.yaml
- path: patches/remove-talos-backup-persistentvolumeclaim-immich-ml-cache.yaml
- path: patches/remove-talos-backup-persistentvolumeclaim-library.yaml
- path: patches/remove-talos-backup-persistentvolumeclaim-nfs-photos.yaml
