- op: remove
  path: "/spec/template/spec/securityContext/runAsUser"
- op: remove
  path: "/spec/template/spec/securityContext/runAsGroup"
- op: remove
  path: "/spec/template/spec/securityContext/fsGroup"
