apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: state
  namespace: radar-ng
  labels:
    backup-exempt:
  annotations:
    storage.vanillax.dev/backup-exempt-reason:
spec:
  storageClassName: truenas-nfs-csi
