apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fizzy
resources:
- "../../../../../manifests/apps/utility/fizzy/base"
- httproute.yaml
patches:
- path: patches/deployment-fizzy.jsonpatch.yaml
  target:
    version: v1
    kind: Deployment
    name: fizzy
    group: apps
    namespace: fizzy
- path: patches/remove-talos-backup-namespace-fizzy.yaml
- path: patches/remove-talos-backup-persistentvolumeclaim-data.yaml
