apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: n8n
resources:
- "../../../../../manifests/apps/home/n8n/base"
- httproute.yaml
patches:
- path: patches/deployment-n8n.jsonpatch.yaml
  target:
    version: v1
    kind: Deployment
    name: n8n
    group: apps
    namespace: n8n
- path: patches/remove-talos-backup-namespace-n8n.yaml
- path: patches/remove-talos-backup-persistentvolumeclaim-data.yaml
