apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-consume-pvc
  namespace: paperless-ngx
  labels:
    backup-exempt:
  annotations:
    storage.vanillax.dev/backup-exempt-reason:
spec:
  storageClassName: local-path
