apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-technitium
  namespace: external-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: external-dns-technitium
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        tsig-secret: '{{ index . "tsig-secret" | trim }}'
  data:
    - secretKey: tsig-secret
      remoteRef:
        key: external-dns-technitium-vanillax
        property: tsig-secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
