apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
  namespace: tubesync
  labels:
    backup-exempt:
  annotations:
    storage.vanillax.dev/backup-exempt-reason:
spec:
  storageClassName: truenas-nfs-csi
  volumeName: ""
