apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: copyparty
resources:
- "../../../../../manifests/apps/media/copyparty/base"
- httproute.yaml
patches:
- path: patches/remove-talos-backup-namespace-copyparty.yaml
- path: patches/remove-talos-backup-persistentvolumeclaim-copyparty-data.yaml
