apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: renovate
resources:
- "../../../../../manifests/apps/development/renovate/base"
patches:
- path: patches/cronjob-renovate.jsonpatch.yaml
  target:
    version: v1
    kind: CronJob
    name: renovate
    group: batch
    namespace: renovate
