apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: truenas-csi

resources:
  - namespace.yaml
  - rbac.yaml
  - configmap.yaml
  - externalsecret.yaml
  - driver.yaml
  - storageclass.yaml
  - volumesnapshotclass.yaml

