apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kiwix
resources:
- "../../../../../manifests/apps/media/kiwix/base"
- httproute.yaml
patches:
- path: patches/deployment-kiwix.jsonpatch.yaml
  target:
    version: v1
    kind: Deployment
    name: kiwix
    group: apps
    namespace: kiwix
- path: patches/remove-talos-backup-persistentvolumeclaim-kiwix-data.yaml
