apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-photos
  namespace: immich
  labels:
    backup-exempt:
  annotations:
    storage.vanillax.dev/backup-exempt-reason:
spec:
  storageClassName: truenas-nfs-csi
  volumeName: ""
