apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: library
  namespace: immich
  labels:
    pvc-plumber.io/enabled:
    pvc-plumber.io/manage-volsync:
    pvc-plumber.io/tier:
    restore-policy:
  annotations:
    argocd.argoproj.io/compare-options:
spec:
  dataSourceRef:
