apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyberchef
  namespace: project-nomad
  labels:
    app: project-nomad-cyberchef
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-nomad-cyberchef
  template:
    metadata:
      labels:
        app: project-nomad-cyberchef
      annotations:
        instrumentation.opentelemetry.io/inject-nodejs: "opentelemetry/default"
    spec:
      containers:
        - name: cyberchef
          image: ghcr.io/gchq/cyberchef:11.2.0
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              cpu: 15m
              memory: 100Mi
            limits:
              cpu: 250m
              memory: 256Mi
