apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: searxng
  labels:
    backup-exempt:
  annotations:
    storage.vanillax.dev/backup-exempt-reason:
spec:
  storageClassName: local-path
