apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: redlib
resources:
- "../../../../../manifests/apps/media/redlib/base"
- httproute.yaml
patches:
- path: patches/deployment-redlib.jsonpatch.yaml
  target:
    version: v1
    kind: Deployment
    name: redlib
    group: apps
    namespace: redlib
