apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-config
  namespace: frigate
  labels:
    pvc-plumber.io/enabled:
    pvc-plumber.io/manage-volsync:
    pvc-plumber.io/tier:
    restore-policy:
  annotations:
    argocd.argoproj.io/compare-options:
spec:
  storageClassName: vanillax-local-rwo
  dataSourceRef:
