apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zomboid-server-files
  namespace: project-zomboid
  labels:
    backup-exempt:
  annotations:
    storage.vanillax.dev/backup-exempt-reason:
