apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meilisearch-pvc
  namespace: karakeep
  labels:
    pvc-plumber.io/enabled:
    pvc-plumber.io/manage-volsync:
    pvc-plumber.io/tier:
    restore-policy:
  annotations:
    argocd.argoproj.io/compare-options:
spec:
  storageClassName: local-path
  dataSourceRef:
